# run: conda env create --file environment.yml
name: CM4X
dependencies:
- matplotlib
- seaborn
- pandas
- xarray
- dask
- zarr
- jupyterlab
- netcdf4
- pip
- pip:
  - git+https://github.com/jkrasting/doralite
  - git+https://github.com/hdrake/gfdl_utils
